#!/bin/bash
# Copies examples from the test directories of RAVEN and HERON to provide examples for users using
# the standalone install version of FORCE.

# Get the RAVEN and HERON locations as arguments "--raven-dir" and "--heron-dir"
# The destination directory is "examples" in the current directory but may be changed with the
# "--dest" argument.
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
EXAMPLES_DIR="$SCRIPT_DIR/examples"

while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --raven-dir)
        RAVEN_DIR="$2"
        shift
        shift
        ;;
        --heron-dir)
        HERON_DIR="$2"
        shift
        shift
        ;;
        --dest)
        EXAMPLES_DIR="$2"
        shift
        shift
        ;;
        *)
        echo "Unknown option: $1"
        exit 1
        ;;
    esac
done

# The examples we want to copy are the RAVEN user_guide tests, the HERON workshop tests, and the
# HERON data directory which contains time series models for those workshop tests.
EXAMPLES=($RAVEN_DIR/tests/framework/user_guide $HERON_DIR/data $HERON_DIR/tests/workshop)
mkdir -p $EXAMPLES_DIR

for ex in ${EXAMPLES[@]}; do
    cp -R "$ex" "$EXAMPLES_DIR"
done

# Clean up the copied examples, removing files and directories created when running the tests.
FILES_TO_REMOVE=("tests" "moped_input.xml" "outer.xml" "inner.xml" "cashflow.xml")
DIRS_TO_REMOVE=("__pycache__" "gold" "*_o")
for filename in ${FILES_TO_REMOVE[@]}; do
    find $EXAMPLES_DIR -name $filename -exec rm {} \;
done
for dirname in ${DIRS_TO_REMOVE[@]}; do
    find $EXAMPLES_DIR -type d -name $dirname -exec rm -r {} \;
done

# If Workbench is installed, convert HERON workshop tests to .heron files
WORKBENCH_BIN=$(dirname $(realpath $(which Workbench)))
XML2EDDI=$(realpath $WORKBENCH_BIN/../rte/util/xml2eddi.py)
if [ -x "$XML2EDDI" ]; then
    for ex in $(find $EXAMPLES_DIR/workshop -name "heron_input*.xml"); do
        python $XML2EDDI $ex
    done
fi
